cmake_path(GET CMAKE_CURRENT_SOURCE_DIR PARENT_PATH REPO_ROOT_DIR)
find_program(BASH_EXECUTABLE bash REQUIRED)
execute_process(
  COMMAND ${BASH_EXECUTABLE} ${REPO_ROOT_DIR}/scripts/get-api-version.sh
  OUTPUT_VARIABLE RVMI_MAJOR_VERSION
  OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)

find_program(
  DOXYGEN_EXECUTABLE
  NAMES doxygen REQUIRED
  HINTS ${DOXYGEN_PATH})

set(DOXYGEN_INPUT_DIRECTORY ${REPO_ROOT_DIR})
configure_file(Doxyfile.in ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile)
message(STATUS "Found Doxygen: ${DOXYGEN_EXECUTABLE}")
add_custom_target(
  docs
  COMMAND ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
  COMMENT "Generating API documentation with Doxygen")
set_target_properties(docs PROPERTIES EXCLUDE_FROM_ALL FALSE)
install(DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/html/" TYPE DOC)
