name: Build and Test
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      NIX_CONFIG: |
        max-jobs = auto
        sandbox-fallback = false
    steps:
      - name: Install Nix
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          curl --proto '=https' --tlsv1.2 -L https://releases.nixos.org/nix/nix-2.35.1/install | sh -s -- --no-daemon
          export USER=$(whoami)
          . "$HOME/.nix-profile/etc/profile.d/nix.sh"
          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH
          echo "NIX_SSL_CERT_FILE=$NIX_SSL_CERT_FILE" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build
        run: |
          nix-build -A rvmi --log-format bar-with-logs
